set(CMAKE_INTERPROCEDURAL_OPTIMIZATION TRUE)


set(CMAKE_CXX_FLAGS_RELEASE "/O2 /Oi /Gy /Gw /GL /Zc:inline /Zc:forScope /Zi /sdl-" CACHE STRING "")
set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "/O2 /Oi /Gy /Gw /GL /Zc:inline /Zc:forScope /Zi /sdl-" CACHE STRING "")
set(CMAKE_CXX_FLAGS_MINSIZEREL "/Gy /Gw /GL /Zc:inline /Zc:forScope /Zi /sdl-" CACHE STRING "")


set(CMAKE_EXE_LINKER_FLAGS_RELEASE "/DEBUG:FULL /OPT:REF /OPT:ICF /LTCG" CACHE STRING "")
set(CMAKE_MODULE_LINKER_FLAGS_RELEASE "/DEBUG:FULL /OPT:REF /OPT:ICF /LTCG" CACHE STRING "")
set(CMAKE_SHARED_LINKER_FLAGS_RELEASE "/DEBUG:FULL /OPT:REF /OPT:ICF /LTCG" CACHE STRING "")
set(CMAKE_STATIC_LINKER_FLAGS_RELEASE "/DEBUG:FULL /OPT:REF /OPT:ICF /LTCG" CACHE STRING "")

set(CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO "/DEBUG:FULL /OPT:REF /OPT:ICF /LTCG" CACHE STRING "")
set(CMAKE_MODULE_LINKER_FLAGS_RELWITHDEBINFO "/DEBUG:FULL /OPT:REF /OPT:ICF /LTCG" CACHE STRING "")
set(CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO "/DEBUG:FULL /OPT:REF /OPT:ICF /LTCG" CACHE STRING "")
set(CMAKE_STATIC_LINKER_FLAGS_RELWITHDEBINFO "/DEBUG:FULL /OPT:REF /OPT:ICF /LTCG" CACHE STRING "")

set(CMAKE_EXE_LINKER_FLAGS_MINSIZEREL "/DEBUG:FULL /OPT:REF /OPT:ICF /LTCG" CACHE STRING "")
set(CMAKE_MODULE_LINKER_FLAGS_MINSIZEREL "/DEBUG:FULL /OPT:REF /OPT:ICF /LTCG" CACHE STRING "")
set(CMAKE_SHARED_LINKER_FLAGS_MINSIZEREL "/DEBUG:FULL /OPT:REF /OPT:ICF /LTCG" CACHE STRING "")
set(CMAKE_STATIC_LINKER_FLAGS_MINSIZEREL "/DEBUG:FULL /OPT:REF /OPT:ICF /LTCG" CACHE STRING "")